name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 14

    - uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 7

    - name: Cache deps
      uses: actions/cache@v1
      id: cache-deps
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-java14-${{ hashFiles('project.clj') }}
        restore-keys: |
              ${{ runner.os }}-java14-

    - name: Run tests for Java 14
      run: |
        lein test-all
